### ISSUE TITLE
Miss File dassl.data

### ISSUE THREAD

**Issue by eee123-123** [yfguo91/NeuroCLIP#1]
Traceback (most recent call last):
  File "../train.py", line 6, in <module>
    from dassl.engine import build_trainer
  File "/root/autodl-tmp/Dassl3D/dassl/engine/__init__.py", line 2, in <module>
    from .trainer import TrainerX, TrainerXU, TrainerBase, SimpleTrainer, SimpleNet # isort:skip
  File "/root/autodl-tmp/Dassl3D/dassl/engine/trainer.py", line 10, in <module>
    from dassl.data import DataManager
ModuleNotFoundError: No module named 'dassl.data'

We follow your readme, but there is an error. I think you miss upload dir and files : Dassl3D/dassl/data/*

**Comment by IceIce1ce** [comment]
+1
